### ISSUE TITLE
Extensions build tracking issue

### ISSUE THREAD

**Issue by kosiokarchev** [kosiokarchev/phytorch#11]
Various code / docs improvements that clarify the extension-building process

- [ ] Boost  is a requirement (but only Preprocessing)
- [ ] #13
- [ ] ninja is a build requirement

**Comment by mjyb16** [comment]
@kosiokarchev Here is a continuation of the hiccups (sadly)....after installing ninja via pip, I tried to compile the extensions but I got a big error, which contains the following traceback:
```
Traceback (most recent call last):
  File "/lustre06/project/6061843/mjybarth/phytorch_env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

```
